version: '2.28.1'

services:

  db:
    image: mysql
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: app
    command:
      - /bin/bash
      - -c
      - |
        celery -A open_weather_integration worker -l info &
        celery -A open_weather_integration flower --port=5555 &
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "5555:5555"
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

volumes:
  db_data: